Repository HeeYoung9/SSB-1st-Project, pull requests merged in 2023-10, with the labels that each got.

#2 feat:test 파일입니다
  3teamProject/src/main/webapp/WEB-INF/web.xml
  3teamProject/src/main/webapp/test.jsp
Labels: help wanted

#4 커밋 연습
  3teamProject/src/main/webapp/loginTest.jsp
Labels: documentation

#6 Feat check
  3teamProject/src/main/webapp/test2.jsp
Labels: 오류

#23 6:24
  3teamProject/src/main/webapp/NewFile.jsp
Labels: enhancement

#30 웹 파일 올려보냅니다.
  3teamProject/src/main/webapp/templete/css/basic.css
  3teamProject/src/main/webapp/templete/guide/Front_Guide.md
  3teamProject/src/main/webapp/templete/guide_img/shopEX1.jpg
  3teamProject/src/main/webapp/templete/guide_img/shopEX2.jpg
  3teamProject/src/main/webapp/templete/guide_img/shopEX3.jpg
  3teamProject/src/main/webapp/templete/guide_img/shopEX4.jpg
  3teamProject/src/main/webapp/templete/guide_img/shopEX5.jpg
  3teamProject/src/main/webapp/templete/guide_img/shopEX6.jpg
  3teamProject/src/main/webapp/templete/home/center.html
  3teamProject/src/main/webapp/templete/home/detail.html
  3teamProject/src/main/webapp/templete/home/example.html
  3teamProject/src/main/webapp/templete/home/goods.html
  3teamProject/src/main/webapp/templete/home/home.html
  3teamProject/src/main/webapp/templete/home/index.html
  3teamProject/src/main/webapp/templete/home/join.html
  3teamProject/src/main/webapp/templete/home/login.html
  3teamProject/src/main/webapp/templete/img/1.jpg
  3teamProject/src/main/webapp/templete/img/2.jpg
  3teamProject/src/main/webapp/templete/img/3.jpg
  3teamProject/src/main/webapp/templete/img/4.jpg
  3teamProject/src/main/webapp/templete/js/active.js
Labels: documentation
